__asm__(
".begin no-transform\n"
".text \n"
".global _" START "\n"
".global " START "\n"
".type   _" START ", @function\n"
".type   " START ", @function\n"
"_" START ":\n"
"" START ":\n"
"	call0	2f\n"
"1:\n"
".align 4\n"
".weak _DYNAMIC\n"
".hidden _DYNAMIC\n"
"	.literal .L0, _DYNAMIC\n"
"	.literal .L1, 1b\n"
"2:\n"
"	mov	a6, a1\n"
"	l32r	a7, .L0\n"
"	l32r	a5, .L1\n"
"	add	a7, a7, a0\n"
"	sub	a7, a7, a5\n"
"	movi	a0, 0\n"
"	call4	" START "_c\n"
".end no-transform\n"
);
