#undef XCHAL_NUM_AREGS
#define XCHAL_NUM_AREGS			__XCHAL_NUM_AREGS

#undef XCHAL_HAVE_S32C1I
#define XCHAL_HAVE_S32C1I		__XCHAL_HAVE_S32C1I

#undef XCHAL_HAVE_EXCLUSIVE
#define XCHAL_HAVE_EXCLUSIVE		__XCHAL_HAVE_EXCLUSIVE
